---
- hosts: ro
  become: true # with oneself
  tasks:
    - name: Update repositories
      apt: update_cache=yes
    - name: Daily update of apt cache
      cron: name="Apt-get update every day" hour="3" minute="0" job="apt-get update"
