---
# We need to add IP masquerading (iptables) and ipv4 forwarding or our
# traffic won't be able to access the internet at large

- name: Ensure we have IPv4 forwarding enabled
  sysctl:
    name="net.ipv4.ip_forward"
    value=1
    sysctl_set=yes
    state=present
    reload=yes
  become: true

- name: Iptables masquerading
  iptables:
    table=nat
    chain=POSTROUTING
    source=10.8.0.0/24
    out_interface={{ ansible_default_ipv4.interface }}
    jump=MASQUERADE
  become: true
