---
- hosts: mail
  become: true
  vars:
    hostname: "mail.vaunt.eu"
    tls: true
    aliases_file: "/etc/aliases"
    tls_only: false
    other_domains: ["vaunt.eu", "naytech.es", "trailbeans.eu"]
    domainkey: true
  handlers:
    - include: 'handlers/main.yml'
  tasks:
    - include: 'tasks/main.yml'
